version: '3.8'
services:
  p2p:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 2
      resources:
        limits:
          cpus: "0.15"
          memory: '35M'
    image: enwaiax/peer2profit:latest
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - email=$email
      - use_proxy=false
    logging: 
      driver: "local"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./proxychains4.conf:/root/proxychains4.conf
