version: '3.8'
services:
  peer2profit:
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
        max_attempts: 2
    image: enwaiax/peer2profit:alpine
    environment: 
      - email=$email
